// backend/seeder.js
const sequelize = require('./config/db');
const models = require('./models'); // Import from models/index.js
require('dotenv').config();

// Sample Admin User
const adminUser = {
  name: 'Admin User',
  email: 'admin@example.com',
  password: 'Admin@123', // Plain-text password (insecure, for testing)
  role: 'admin',
};

const sampleProducts = [
  // MEN - Shirts
  {
    name: 'Men Shirt 1',
    description: 'Premium cotton shirt for formal occasions',
    category: 'Shirts',
    gender: 'Men',
    size: 'M', // Changed to string
    color: 'White', // Changed to string
    brand: 'Zara',
    price: 39.99,
    featured: true,
    countInStock: 10,
    image: '/images/men-shirt1.jpg',
    onSale: true, // Added for sale filter
    salePrice: 29.99, // Added for sale filter
  },
  {
    name: 'Men Shirt 2',
    description: 'Casual slim-fit shirt',
    category: 'Shirts',
    gender: 'Men',
    size: 'L',
    color: 'Black',
    brand: 'H&M',
    price: 34.99,
    countInStock: 8,
    image: '/images/men-shirt2.jpg',
  },
  {
    name: 'Men Shirt 3',
    description: 'Lightweight summer shirt',
    category: 'Shirts',
    gender: 'Men',
    size: 'S',
    color: 'White',
    brand: 'Kohl',
    price: 29.99,
    countInStock: 9,
    image: '/images/men-shirt3.jpg',
    onSale: true,
    salePrice: 24.99,
  },
  {
    name: 'Men Shirt 4',
    description: 'Formal dress shirt',
    category: 'Shirts',
    gender: 'Men',
    size: 'XL',
    color: 'Black',
    brand: "Levi's",
    price: 44.99,
    countInStock: 6,
    image: '/images/men-shirt4.jpg',
  },
  {
    name: 'Men Shirt 5',
    description: 'Stylish casual shirt',
    category: 'Shirts',
    gender: 'Men',
    size: 'M',
    color: 'White',
    brand: 'Jack & Jones',
    price: 36.99,
    countInStock: 7,
    image: '/images/men-shirt5.jpg',
  },
  {
    name: 'Men Shirt 6',
    description: 'Classic oxford shirt',
    category: 'Shirts',
    gender: 'Men',
    size: 'L',
    color: 'Black',
    brand: 'Allen Solly',
    price: 42.99,
    countInStock: 10,
    image: '/images/men-shirt6.jpg',
  },

  // MEN - T-Shirts
  {
    name: 'Men T-Shirt 1',
    description: 'Comfortable cotton t-shirt',
    category: 'T-Shirts',
    gender: 'Men',
    size: 'M',
    color: 'White',
    brand: 'Nike',
    price: 29.99,
    countInStock: 12,
    image: '/images/men-tshirt1.jpg',
  },
  {
    name: 'Men T-Shirt 2',
    description: 'Athletic fit t-shirt',
    category: 'T-Shirts',
    gender: 'Men',
    size: 'L',
    color: 'Black',
    brand: 'Adidas',
    price: 32.99,
    countInStock: 14,
    image: '/images/men-tshirt2.jpg',
    onSale: true,
    salePrice: 27.99,
  },
  {
    name: 'Men T-Shirt 3',
    description: 'Casual graphic t-shirt',
    category: 'T-Shirts',
    gender: 'Men',
    size: 'S',
    color: 'White',
    brand: 'Puma',
    price: 24.99,
    countInStock: 9,
    image: 'images/men-tshirt3.jpg',
  },
  {
    name: 'Men T-Shirt 4',
    description: 'Sporty t-shirt',
    category: 'T-Shirts',
    gender: 'Men',
    size: 'XL',
    color: 'Black',
    brand: 'Reebok',
    price: 26.99,
    countInStock: 11,
    image: '/images/men-tshirt4.jpg',
  },
  {
    name: 'Men T-Shirt 5',
    description: 'Classic crew neck t-shirt',
    category: 'T-Shirts',
    gender: 'Men',
    size: 'M',
    color: 'White',
    brand: "Levi's",
    price: 28.99,
    countInStock: 10,
    image: '/images/men-tshirt5.jpg',
  },
  {
    name: 'Men T-Shirt 6',
    description: 'Premium t-shirt',
    category: 'T-Shirts',
    gender: 'Men',
    size: 'L',
    color: 'Black',
    brand: 'Tommy Hilfiger',
    price: 35.99,
    countInStock: 8,
    image: '/images/men-tshirt6.jpg',
  },

  // MEN - Pants
  {
    name: 'Men Pants 1',
    description: 'Slim-fit jeans',
    category: 'Pants',
    gender: 'Men',
    size: 'M',
    color: 'Black',
    brand: "Levi's",
    price: 49.99,
    countInStock: 10,
    image: '/images/men-pants1.jpg',
  },
  {
    name: 'Men Pants 2',
    description: 'Chino pants',
    category: 'Pants',
    gender: 'Men',
    size: 'L',
    color: 'White',
    brand: 'Zara',
    price: 54.99,
    countInStock: 6,
    image: '/images/men-pants2.jpg',
  },
  {
    name: 'Men Pants 3',
    description: 'Casual trousers',
    category: 'Pants',
    gender: 'Men',
    size: 'S',
    color: 'Black',
    brand: 'H&M',
    price: 44.99,
    countInStock: 7,
    image: '/images/men-pants3.jpg',
  },
  {
    name: 'Men Pants 5',
    description: 'Rugged cargo pants',
    category: 'Pants',
    gender: 'Men',
    size: 'XL',
    color: 'White',
    brand: 'Wrangler',
    price: 39.99,
    countInStock: 10,
    image: '/images/men-pants4.jpg',
  },

  // MEN - Shoes
  {
    name: 'Men Shoes 1',
    description: 'Running sneakers',
    category: 'Shoes',
    gender: 'Men',
    size: 'M',
    color: 'White',
    brand: 'Nike',
    price: 79.99,
    featured: true,
    countInStock: 15,
    image: '/images/men-shoes1.jpg',
    onSale: true,
    salePrice: 69.99,
  },
  {
    name: 'Men Shoes 2',
    description: 'Casual sneakers',
    category: 'Shoes',
    gender: 'Men',
    size: 'L',
    color: 'Black',
    brand: 'Adidas',
    price: 84.99,
    countInStock: 10,
    image: '/images/men-shoes2.jpg',
  },
  {
    name: 'Men Shoes 5',
    description: 'Outdoor boots',
    category: 'Shoes',
    gender: 'Men',
    size: 'XL',
    color: 'Black',
    brand: 'Woodland',
    price: 89.99,
    countInStock: 8,
    image: '/images/men-shoes3.jpg',
  },

  // WOMEN - Shirts
  {
    name: 'Women Shirt 1',
    description: 'Elegant blouse',
    category: 'Shirts',
    gender: 'Women',
    size: 'M',
    color: 'White',
    brand: 'Zara',
    price: 39.99,
    countInStock: 10,
    image: '/images/women-shirt1.jpg',
  },
  {
    name: 'Women Shirt 2',
    description: 'Casual top',
    category: 'Shirts',
    gender: 'Women',
    size: 'S',
    color: 'Black',
    brand: 'H&M',
    price: 34.99,
    countInStock: 8,
    image: '/images/women-shirt2.jpg',
  },
  {
    name: 'Women Shirt 3',
    description: 'Formal blouse',
    category: 'Shirts',
    gender: 'Women',
    size: 'L',
    color: 'White',
    brand: "Levi's",
    price: 44.99,
    featured: true,
    countInStock: 6,
    image: '/images/women-shirt3.jpg',
    onSale: true,
    salePrice: 39.99,
  },

  // WOMEN - T-Shirts
  {
    name: 'Women T-Shirt 1',
    description: 'Soft cotton t-shirt',
    category: 'T-Shirts',
    gender: 'Women',
    size: 'M',
    color: 'White',
    brand: 'Nike',
    price: 29.99,
    countInStock: 12,
    image: '/images/women-tshirt1.jpg',
  },
  {
    name: 'Women T-Shirt 2',
    description: 'Graphic t-shirt',
    category: 'T-Shirts',
    gender: 'Women',
    size: 'L',
    color: 'Black',
    brand: 'Adidas',
    price: 32.99,
    countInStock: 14,
    image: '/images/women-tshirt2.jpg',
  },
  {
    name: 'Women T-Shirt 3',
    description: 'Casual t-shirt',
    category: 'T-Shirts',
    gender: 'Women',
    size: 'S',
    color: 'White',
    brand: 'Zara',
    price: 24.99,
    countInStock: 9,
    image: '/images/women-tshirt3.jpg',
  },
  {
    name: 'Women T-Shirt 4',
    description: 'Sporty t-shirt',
    category: 'T-Shirts',
    gender: 'Women',
    size: 'XL',
    color: 'Black',
    brand: 'H&M',
    price: 26.99,
    countInStock: 11,
    image: '/images/women-tshirt4.jpg',
  },
  {
    name: 'Women T-Shirt 5',
    description: 'Classic t-shirt',
    category: 'T-Shirts',
    gender: 'Women',
    size: 'M',
    color: 'White',
    brand: "Levi's",
    price: 28.99,
    countInStock: 10,
    image: '/images/women-tshirt5.jpg',
  },

  // WOMEN - Pants
  {
    name: 'Women Pants 1',
    description: 'High-waisted jeans',
    category: 'Pants',
    gender: 'Women',
    size: 'M',
    color: 'Black',
    brand: "Levi's",
    price: 49.99,
    countInStock: 10,
    image: '/images/women-pants1.jpg',
    onSale: true,
    salePrice: 44.99,
  },
  {
    name: 'Women Pants 2',
    description: 'Tailored trousers',
    category: 'Pants',
    gender: 'Women',
    size: 'L',
    color: 'White',
    brand: 'Zara',
    price: 54.99,
    countInStock: 6,
    image: '/images/women-pants2.jpg',
  },
  {
    name: 'Women Pants 3',
    description: 'Casual pants',
    category: 'Pants',
    gender: 'Women',
    size: 'S',
    color: 'Black',
    brand: 'H&M',
    price: 44.99,
    countInStock: 7,
    image: '/images/women-pants3.jpg',
  },
  {
    name: 'Women Pants 4',
    description: 'Comfortable chinos',
    category: 'Pants',
    gender: 'Women',
    size: 'XL',
    color: 'White',
    brand: 'Allen Solly',
    price: 48.99,
    countInStock: 8,
    image: '/images/women-pants4.jpg',
  },
];

const seedDatabase = async () => {
  try {
    await sequelize.sync({ force: true }); // Drops and recreates tables

    // Create admin user
    const createdAdmin = await models.User.create(adminUser);
    console.log('Admin user created:', createdAdmin.email);

    // Add user ID to products
    const productsWithUser = sampleProducts.map((product) => ({
      ...product,
      user: createdAdmin.id, // Assign admin as creator
    }));

    // Seed products
    await models.Product.bulkCreate(productsWithUser);
    console.log('Products imported to PostgreSQL!');

    process.exit();
  } catch (err) {
    console.error('Error seeding data:', err);
    process.exit(1);
  }
};

seedDatabase();